# This is a basic workflow to help you get started with Actions

name: plsql-table-unit-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
        with:
          name: oracle/docker-images
          ref: refs/heads/release

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          oracle/docker-images/OracleDatabase/SingleInstance/buildContainerImage.sh
          #
          #docker run --name oracle-18-4-xe \
          #-p 1521:1521 -p 5500:5500 \
          #-e ORACLE_PWD=a_dumb_pw_567 \
          #-e ORACLE_CHARACTERSET=AL32UTF8 \
          #oracle/database:18.4.0-xe 
          #see for reference: https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md
